version: '3.3'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    volumes:
        - rabbit-volume-etc:/etc/rabbitmq/
        - rabbit-volume-data:/var/lib/rabbitmq/
        - rabbit-volume-logs:/var/log/rabbitmq/
    environment:
        RABBITMQ_ERLANG_COOKIE: "EXAMPLECOOKIE"
        RABBITMQ_DEFAULT_USER: root
        RABBITMQ_DEFAULT_PASS: root
    ports:
        - "18003:5672"
        - "18004:15672"
volumes:
  rabbit-volume-etc:
  rabbit-volume-data:
  rabbit-volume-logs: